### ISSUE TITLE
TypeError: redlock_1.default is not a constructor

### ISSUE THREAD

**Issue by GO-DIE** [mike-marcacci/node-redlock#105]
**ts code:**
```typescript
import Client from 'ioredis';
import Redlock from 'redlock';

const redisA = new Client({ host: 'ubuntu' });

const redlock = new Redlock(
  // You should have one client for each independent redis node
  // or cluster.
  [redisA],
  {
    driftFactor: 0.01, // multiplied by lock ttl to determine drift time
    retryCount: 10,
    retryDelay: 200, // time in ms
    retryJitter: 200, // time in ms
  },
);
```

**error:**
const redlock = new Redlock(
                ^
TypeError: redlock_1.default is not a constructor
    at Object.<anonymous> (c:\Users\GO_DIE\Desktop\nest-study\test\1.ts:6:17)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Module.m._compile (C:\Users\GO_DIE\AppData\Roaming\nvm\v14.4.0\node_modules\ts-node\src\index.ts:1056:23) 
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\GO_DIE\AppData\Roaming\nvm\v14.4.0\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)    at main (C:\Users\GO_DIE\AppData\Roaming\nvm\v14.4.0\node_modules\ts-node\src\bin.ts:198:14)
    at Object.<anonymous> (C:\Users\GO_DIE\AppData\Roaming\nvm\v14.4.0\node_modules\ts-node\src\bin.ts:288:3)    
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by leobel** [comment]
Hi, I have the same issue from a NestJS app

**Comment by Naeemo** [comment]
``` TypeScript
import * as Redlock from 'redlock';
```

**Comment by mike-marcacci** [comment]
I just published `v5.0.0-beta.1` which now publishes both ESM and CJS versions.

**Comment by YuriyTigiev** [comment]
Hello, 

I have a similar error for  "redlock": "^5.0.0-beta.1",. 

```
const redis = require('redis')
const Redlock = require('redlock')
const { promisify } = require('util')

const redisClient = redis.createClient('6379', '127.0.0.1')
const redisSet = promisify(redisClient.set).bind(redisClient)
const redisGet = promisify(redisClient.get).bind(redisClient)

const redlock = new Redlock(
    [redisClient],
    {
        driftFactor: 0.01,
        retryCount:  -1,
        retryDelay:  200,
        retryJitter:  200
    }
)

const redlock = new Redlock(
                ^

TypeError: Redlock is not a constructor
    at Object.<anonymous> (/var/www/html/screener.market/app.js:46:17)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/var/www/html/screener.market/bin/www.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

```


```
  "dependencies": {
    "bootstrap": "^5.1.3",
    "bootstrap-select": "^1.13.18",
    "ccxt": "^1.61.24",
    "express": "^4.17.1",
    "ioredis": "^4.28.2",
    "morgan": "^1.10.0",
    "pug": "^3.0.2",
    "redis": "^4.0.0",
    "redlock": "^5.0.0-beta.1",
    "serve-favicon": "^2.5.0",
    "util": "^0.12.4"
  }
```

**Comment by mike-marcacci** [comment]
Hy @YuriyTigiev,

I think your issue is a simple one 😄

Per the [Use in CommonJS Projects](https://github.com/mike-marcacci/node-redlock#use-in-commonjs-projects) section of the README:

> Beginning in version 5, this package is published primarily as an ECMAScript module. While this is universally accepted as the format of the future, there remain some interoperability quirks when used in CommonJS node applications. For major version 5, this package **also** distributes a copy transpiled to CommonJS. Please ensure that your project either uses either the ECMAScript or CommonJS version **but NOT both**.
> 
> The `Redlock` class is published as the "default" export, and can be imported with:
> 
> ```ts
> const { default: Redlock } = require("redlock");
> ```
> 
> In version 6, this package will stop distributing the CommonJS version.

Updating to your import statement to the above _should_ fix your issue!

**Comment by YuriyTigiev** [comment]
Is the code below correct? 
If yes then I get the same error. 

redlock.js 

```
var Client  = require("ioredis");
const { default: Redlock } = require("redlock");

const redisClient = new Client({ host: "127.0.0.1" });

var redlock = new Redlock(
  // You should have one client for each independent redis node
  // or cluster.
  [redisClient],
  {
    // The expected clock drift; for more details see:
    // http://redis.io/topics/distlock
    driftFactor: 0.01, // multiplied by lock ttl to determine drift time

    // The max number of times Redlock will attempt to lock a resource
    // before erroring.
    retryCount: 10,

    // the time in ms between attempts
    retryDelay: 200, // time in ms

    // the max time in ms randomly added to retries
    // to improve performance under high contention
    // see https://www.awsarchitectureblog.com/2015/03/backoff.html
    retryJitter: 200, // time in ms

    // The minimum remaining time on a lock before an extension is automatically
    // attempted with the `using` API.
    automaticExtensionThreshold: 500, // time in ms
  }
);

```


index.js
```

"use strict"
var redlock = require('./redlock.js')

async function fetchOHLCV(exchange_id, symbol, timeframe, since, limit) {


let lock = await redlock.acquire(["a"], 5000);
try {
  // Do something...
  //await something();

  // Extend the lock.
  lock = await lock.extend(5000);

  // Do something else...
  //await somethingElse();
} finally {
  // Release the lock.
  await lock.release();
}

}
```
