### ISSUE TITLE
Locking key error 

### ISSUE THREAD

**Issue by eric-tylan** [mike-marcacci/node-redlock#115]
Sorry to bother you. 

I dont undersatnd why but it seems work fine at localhost but keeps telling me the key exists when I deployed on the cloud whereas if i manually check the key, it tells me it doesnt exists. 

anyway, this is my code and the error returned by client error event. 

``` Typescript 
     public async useMutex(cb: Function, channelName: string, JJUid: number): Promise<any> {
        let mutex: string[];

        if (channelName && JJUid) mutex = [this.mutex + "channel-" + channelName, this.mutex + "user-" + JSON.stringify(JJUid)];
        else if (channelName) mutex = [this.mutex + "channel-" + channelName];
        else mutex = [this.mutex + "user-" + JSON.stringify(JJUid)];
 
        return redlock.lock(mutex, 3000).then((lock) => {
            return Promise.resolve(cb()).then(
                (result) => {
                    lock.unlock().catch((errFromUnlocking) => {
                        throwError(ErrorList.Data.redis, errFromUnlocking, "useMutex-redis");
                    });
                    return result;
                },
                (errFromCallback) => {
                    lock.unlock().catch((errFromUnlocking) => {
                        throwError(ErrorList.Data.redis, errFromUnlocking, "useMutex-redis");
                    });
                    throw errFromCallback;
                }
            );
        });
    }
```
here is the configuration 

``` Typescript 
const redlock = new Redlock([RedisClient], {
    retryCount: 3, // retry chance
    retryDelay: 1000, // 1s delay retry
    retryJitter: 200, // 0.2s jitter
});
redlock.on("clientError", function (err) {
    Socket.errMsg(err);
    console.error("A redis error has occurred", err);
});
``` 

And finnaly here is the err msg 
``` 
3|media-demo-test  | 2021-11-05 16:36 +08:00: A redis error has occurred ReplyError: ERR bad lua script for redis cluster, all the keys that the script uses should be passed using the KEYS array, and KEYS should not be in expression
3|media-demo-test  | 2021-11-05 16:36 +08:00:     at parseError (/usr/project/media/media-demo/node_modules/redis/node_modules/redis-parser/lib/parser.js:179:12)
3|media-demo-test  | 2021-11-05 16:36 +08:00:     at parseType (/usr/project/media/media-demo/node_modules/redis/node_modules/redis-parser/lib/parser.js:302:14) {
3|media-demo-test  | 2021-11-05 16:36 +08:00:   command: 'EVAL',
3|media-demo-test  | 2021-11-05 16:36 +08:00:   args: [
3|media-demo-test  | 2021-11-05 16:36 +08:00:     '\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\t-- Return 0 if an entry already exists.\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\tfor i, key in ipairs(KEYS) do\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\t\tif redis.call("exists", key) == 1 then\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\t\t\treturn 0\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\t\tend\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\tend\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\t-- Create an entry for each provided key.\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\tfor i, key in ipairs(KEYS) do\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\t\tredis.call("set", key, ARGV[1], "PX", ARGV[2])\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\tend\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\t-- Return the number of entries added.\n' +
3|media-demo-test  | 2021-11-05 16:36 +08:00:       '\treturn #KEYS\n',
3|media-demo-test  | 2021-11-05 16:36 +08:00:     1,
3|media-demo-test  | 2021-11-05 16:36 +08:00:     'mutex-demo-user-11111',
3|media-demo-test  | 2021-11-05 16:36 +08:00:     '9a06d6190abe86ce8c0301ccea3dd0e6',
3|media-demo-test  | 2021-11-05 16:36 +08:00:     3000
3|media-demo-test  | 2021-11-05 16:36 +08:00:   ],
3|media-demo-test  | 2021-11-05 16:36 +08:00:   code: 'ERR'
3|media-demo-test  | 2021-11-05 16:36 +08:00: }

``` 

Also, could that because I am using redis instead of ioredis ?

**Comment by eric-tylan** [comment]
NVM find the problem. its because the cloud server has some regulation aginst the lua script. sorry for bother everybody
