### ISSUE TITLE
Unable to reach quorum

### ISSUE THREAD

**Issue by paymog** [mike-marcacci/node-redlock#168]
I'm having some trouble using this library. I have an endpoint which gets called twice upon page load and I'm trying to use a lock to perform sensitive database operations safely. 

I'm using this library and I keep getting the following error in unusual ways which I haven't been able to figure out (maybe I have the library misconfigured?). Here's the code I'm using to initialize redlock:

```
import { getRedisURI } from './settings/settings.js';
import Redis from 'ioredis';
import Redlock from 'redlock';

export const redis = new Redis(getRedisURI());
export const redlock = new Redlock([redis]);
```

here's the code which does the sensitive database work:

```
async function createNewScheduleCardsIfNecessary(tripId) {
  let lock;
  console.log('attempting to make new schedule card items for trip', tripId);

  try {
    lock = await redlock.acquire([`${tripId}`], 5000, {
      retryDelay: 1000,
      retryCount: 30,
      automaticExtensionThreshold: 100,
      retryJitter: 1000,
    });
    console.log('acquired lock', tripId);
    const expectedNumberOfCards = await getExpectedNumberOfScheduleCards(tripId);
    const currentCards = await ScheduleCards.find({
      tripId,
    }).toArray();

    await createMissingScheduleCards(currentCards, expectedNumberOfCards, tripId);
    console.log('finished making schedule cards', tripId);
  } finally {
    if (lock) {
      console.log('releasing lock', tripId);
      await lock.release();
    }
  }
  console.log('all redlock stuff finished for trip', tripId);
}
```

here's the full output I'm getting:

```
Server running at http://localhost:5001/graphql


schedule cards called for trip vMEKsgzFy9EGdQKbp <------------ this indicates a request came in from the web 
attempting to make new schedule card items for trip vMEKsgzFy9EGdQKbp
acquired lock vMEKsgzFy9EGdQKbp
schedule cards called for trip vMEKsgzFy9EGdQKbp <--------------- here's the second request from the web
attempting to make new schedule card items for trip vMEKsgzFy9EGdQKbp
need to create schedule card for trip { part: 'morning', i: 0 }
need to create schedule card for trip { part: 'morning', i: 1 }
need to create schedule card for trip { part: 'morning', i: 2 }
need to create schedule card for trip { part: 'morning', i: 3 }
need to create schedule card for trip { part: 'morning', i: 4 }
need to create schedule card for trip { part: 'afternoon', i: 0 }
need to create schedule card for trip { part: 'afternoon', i: 1 }
need to create schedule card for trip { part: 'afternoon', i: 2 }
need to create schedule card for trip { part: 'afternoon', i: 3 }
need to create schedule card for trip { part: 'afternoon', i: 4 }
need to create schedule card for trip { part: 'evening', i: 0 }
need to create schedule card for trip { part: 'evening', i: 1 }
need to create schedule card for trip { part: 'evening', i: 2 }
need to create schedule card for trip { part: 'evening', i: 3 }
need to create schedule card for trip { part: 'evening', i: 4 }
need to create schedule card for trip { part: 'lodging', i: 0 }
need to create schedule card for trip { part: 'lodging', i: 1 }
need to create schedule card for trip { part: 'lodging', i: 2 }
need to create schedule card for trip { part: 'lodging', i: 3 }
need to create schedule card for trip { part: 'lodging', i: 4 }
finished making schedule cards vMEKsgzFy9EGdQKbp
releasing lock vMEKsgzFy9EGdQKbp
ExecutionError: The operation was unable to achieve a quorum during its retry window.
    at Redlock._execute (file:///Users/paymahn/code/tripvector/tripvector-mono/backend/node_modules/redlock/dist/esm/index.js:290:23)
    at async createNewScheduleCardsIfNecessary (file:///Users/paymahn/code/tripvector/tripvector-mono/backend/api/scheduleCards/graphql/queries.js:143:7)
    at async Object.scheduleCards (file:///Users/paymahn/code/tripvector/tripvector-mono/backend/api/scheduleCards/graphql/queries.js:153:5) {
  attempts: [
    Promise { [Object] },
    Promise { [Object] },
    Promise { [Object] },
    Promise { [Object] },
    Promise { [Object] },
    Promise { [Object] },
    Promise { [Object] },
    Promise { [Object] },
    Promise { [Object] },
    Promise { [Object] },
    Promise { [Object] }
  ]
}
ExecutionError: The operation was unable to achieve a quorum during its retry window.
    at Redlock._execute (file:///Users/paymahn/code/tripvector/tripvector-mono/backend/node_modules/redlock/dist/esm/index.js:290:23)
    at async Redlock.acquire (file:///Users/paymahn/code/tripvector/tripvector-mono/backend/node_modules/redlock/dist/esm/index.js:207:34)
    at async createNewScheduleCardsIfNecessary (file:///Users/paymahn/code/tripvector/tripvector-mono/backend/api/scheduleCards/graphql/queries.js:126:12)
    at async Object.scheduleCards (file:///Users/paymahn/code/tripvector/tripvector-mono/backend/api/scheduleCards/graphql/queries.js:153:5) {
  attempts: [
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }, Promise { [Object] },
    Promise { [Object] }
  ]
}
```

The time between the `acquired lock` and `releasing lock` log lines is around 1 second but for some reason, even with the generous retry policy I'm seeing redlock fail consistently.

The top stack trace includes line 143 which is the line where I release the lock. The bottom stack trace include line 126 which is where I acquire the lock.

I've tried using `redlock.using` as well but had the same results. I've downloaded a redis gui to inspect my local redis instance to see if there are any spurious keys but haven't been able to find any. 

Here's my package.json:

```
    "@babel/runtime": "^7.16.3",
    "@graphql-tools/schema": "^8.3.1",
    "apollo-server-express": "^3.5.0",
    "axios": "^0.26.1",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.19.0",
    "chalk": "^4.1.2",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.6",
    "cors": "^2.8.5",
    "crypto-extra": "^1.0.1",
    "dayjs": "^1.10.7",
    "ejs": "^3.1.6",
    "express": "^4.17.1",
    "graphql": "^16.0.1",
    "graphql-redis-subscriptions": "^2.4.2",
    "graphql-subscriptions": "^2.0.0",
    "graphql-ws": "^5.7.0",
    "html-to-text": "^8.1.0",
    "immutability-helper": "^3.1.1",
    "ioredis": "^5.0.4",
    "jsonwebtoken": "^8.5.1",
    "juice": "^8.0.0",
    "lodash-es": "^4.17.21",
    "moment": "^2.29.3",
    "mongo-uri-tool": "^1.0.1",
    "mongodb": "^4.2.0",
    "nodemailer": "^6.7.2",
    "ps-node": "^0.1.6",
    "redlock": "^5.0.0-beta.2",
    "serve-favicon": "^2.5.0",
    "speakingurl": "^14.0.1",
    "ws": "^8.5.0"
```

**Comment by paymog** [comment]
Downgrading to version 4 for redlock and ioredis solved my issue completely, I guess there's a bug with the v5 implementation.

**Comment by kylecannon** [comment]
having this same issue too.

**Comment by jskorlol** [comment]
I have the same problem, is there any solution?

**Comment by paymog** [comment]
@jskorlol try downgrading to version 4 of this package and ioredis

**Comment by kylecannon** [comment]
yeah, the problem is i would really like the lock auto extend functionality.

**Comment by jjm340** [comment]
I'm having this problem too, we use redlock v4 to great success so I'm downgrading for now.

**Comment by hlongvu** [comment]
any update on this, I am having this problem too

**Comment by Dakuan** [comment]
We are still seeing this intermittently even with `redlock.using`

**Comment by jketcham** [comment]
I was also running into this on version `5.0.0-beta.2` while using `redlock.using`, here's the relevant stack trace:

```
ExecutionError: The operation was unable to achieve a quorum during its retry window.
    at Redlock._execute (file:///workspace/node_modules/redlock/dist/esm/index.js:290:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Redlock.acquire (file:///workspace/node_modules/redlock/dist/esm/index.js:207:34)
    at async Redlock.using (file:///workspace/node_modules/redlock/dist/esm/index.js:448:20)
    ... my code ...
```

With the call to using looking like:
```js
await redlock.using([lockId], 5000, async (signal) => { ... my code ... });
```

The problem seems to occur when the same resource is trying to be locked multiple times in close succession. Increasing the `retryCount` and `retryDelay` (to `30` and `1000` respectively for my setup) prevented the quorum error from throwing, but then I'd still have errors about not being able to extend an already expired lock.

**Comment by paulohlips** [comment]
Hi folks, I faced this problem, but was a mistake in my code. 

I was trying to aquire and make a set in the same key, as:

`const main = async () => {
  try {
    const lock = await redlock.acquire(['**myKey**'], 1000);
    redisClient.set("**myKey**", "newValue")
    await lock.release();
  } catch (e) {
    console.error(e);
    throw e;
  }
};
`

But this way is wrong because we need to aquire a **resourceKey** like "myLokedResouce:myKey" and then make changes in our **key** (is tihis exemple "myKey") and after release the lock on "myLokedResouce:myKey". Now my code search by "resourceKey" to make changes in my "key" like:

`
const key = "project"
const value = "CONFLICT"
const resource = `locks:${key}`
const lockTtl = 66000

async function lockAndSet(resource , lockTtl) {
  const lock = await redlock.acquire([resource], lockTtl)

  try {
    await redisSet(key, value)
    console.log('Time finished, key unlocked!')
    await lock.release()

  } catch (e) {
    console.log(`catchError: ${e}`)
  }
} 

lockAndSet(resource, lockTtl)
`

**Comment by shengjie9** [comment]
I have same issue too! How to fix?

**Comment by shengjie9** [comment]
I have issue too! I have no idea. I read code and find `client.evalsha(args)` function throw error `Error: node_redis: The EVALSHA command contains a invalid argument type.`,then I have no idea

**Comment by reinoute** [comment]
I believe this is a bug in the v5 implementation. When you attempt to set a lock using `acquire()` and the resource is locked, Redlock will throw an `ExecutionError`, but it should throw a `ResourceLockedError` (as it did in the previous version).

**Comment by leobel** [comment]
Any update on this? The only workaround is downgrade to v4 both redlock and ioredis?

**Comment by vi93a** [comment]
I was facing same issue but it was because of me passing redis client as `undefined`. You can debug this issue by logging in error event handler of redlock.

**Comment by gdelory** [comment]
We are also hitting this issue as soon as 2 process are trying to lock the same resource. This is 100% reproduceable:

```
const { client } = require('./utils/RedisClient')
const { default: Redlock } = require('redlock')

const redlock = new Redlock(
  [client], {
    driftFactor: 0.01, // multiplied by lock ttl to determine drift time
    retryCount: 300,
    retryDelay: 1000, // time in ms
    retryJitter: 200, // time in ms
    automaticExtensionThreshold: 500, // time in ms
  }
)

const withLock = async (resourceToLock, doSomethingWithLock) => {
  let lock = await redlock.acquire([resourceToLock], 30000)
  let result
  try {
    result = await doSomethingWithLock()
  } finally {
    await lock.release()
  }
  return result
}

const wait = ms => new Promise((resolve) => setTimeout(resolve, ms))

const main = async () => {
  const name = process.argv[2]
  try {
    await withLock('superId', async () => {
      console.log('start wait', name)
      await wait(30000)
      console.log('done waiting', name)
    })
    console.log('all done', name)
    
  } catch (error) {
    console.error(error.message)
  }
  process.exit()
  
}

main()
```

Result when running twice this process with p1 and p2 name:
```
start wait p2
done waiting p2
The operation was unable to achieve a quorum during its retry window.
```

**Comment by manomano** [comment]
> Downgrading to version 4 for redlock and ioredis solved my issue completely, I guess there's a bug with the v5 implementation.

Can you specify concrete version?

**Comment by aduca98** [comment]
Any status update on the fix? It looks like a few PRs were made (I saw another github thread). where does this stand? I am also having this issue where I do not know the TTL upfront so I need the autoextending and it is giving me problems.

**Comment by EmilSabri** [comment]
> Hi folks, I faced this problem, but was a mistake in my code.
> 
> I was trying to aquire and make a set in the same key, as:
> 
> const main = async () => { try { const lock = await redlock.acquire(['myKey], 1000); redisClient.set("myKey", "newValue") await lock.release(); } catch (e) { console.error(e); throw e; } }
> 
> But this way is wrong because we need to aquire a **resourceKey** like "myLokedResouce:myKey" and then make changes in our **key** (is tihis exemple "myKey") and after release the lock on "myLokedResouce:myKey". Now my code search by "resourceKey" to know if can makes changes in my "key" like:
> 
> const key = "project" const value = "CONFLICT" const resource = `locks:${key}` const lockTtl = 66000
> 
> async function lockAndSet(resource , lockTtl) { const lock = await redlock.acquire([resource], lockTtl)
> 
> try { await redisSet(key, value) console.log('Time finished, key unlocked!') await lock.release()
> 
> } catch (e) { console.log(e) } }
> 
> lockAndSet(resource, lockTtl)

Adding the resource key worked for me on ^5.0.0-beta.2

**Comment by bukovacRobert** [comment]
Hey everyone! 👋 
Is there a fix for this issue yet, or has anyone found a workaround? 
Are we all just waiting for the stable v5 release, or is there something I’ve missed? Any info or updates would be super helpful!

**Comment by ravi9989** [comment]
I also faced the same problem, but the solution is around the duration of lock which you mentioned. 
I mean :
You are configuring 400ms as duration of lock
and trying to release the lock at 600th ms[trying to release already expired lock]. Which could cause this issue.

**Comment by ifeLight** [comment]
So currently, with what is available, to prevent errors, you have to give a timelock beyond the duration of your service.

That is if your service will run for 2 seconds, make it 5s to be safe, so as long the service does not crash, it will notify Redis when it is done for another service to acquire the lock. Or you can use the `extend` method to extend the lock when your service will take longer time.

**Comment by divmgl** [comment]
Just stumbled on this now. Downgrading to 4.2.0 was the only solution. As far as I can tell it works with the latest version of `ioredis` but you'll need to add a `@ts-expect-error` because the two signatures are the identical between the expected version of `ioredis` and the latest.

**Comment by UgurGumushan** [comment]
> Hi folks, I faced this problem, but was a mistake in my code.
> 
> I was trying to aquire and make a set in the same key, as:
> 
> const main = async () => { try { const lock = await redlock.acquire(['myKey], 1000); redisClient.set("myKey", "newValue") await lock.release(); } catch (e) { console.error(e); throw e; } }
> 
> But this way is wrong because we need to aquire a **resourceKey** like "myLokedResouce:myKey" and then make changes in our **key** (is tihis exemple "myKey") and after release the lock on "myLokedResouce:myKey". Now my code search by "resourceKey" to know if can makes changes in my "key" like:
> 
> const key = "project" const value = "CONFLICT" const resource = `locks:${key}` const lockTtl = 66000
> 
> async function lockAndSet(resource , lockTtl) { const lock = await redlock.acquire([resource], lockTtl)
> 
> try { await redisSet(key, value) console.log('Time finished, key unlocked!') await lock.release()
> 
> } catch (e) { console.log(e) } }
> 
> lockAndSet(resource, lockTtl)

This worked for me. Thank you. 
So this project did not document how to use resource keys. (Please update the *.md if possible)

**Summary:** 
We should not use the key of the locked resource as resource keys and prepend something like "redlock:user1111" and this refers to the lock, like a pointer and not the actual item.

**Comment by BernalCarlos** [comment]
> Hi folks, I faced this problem, but was a mistake in my code.
> 
> I was trying to aquire and make a set in the same key, as:
> 
> const main = async () => { try { const lock = await redlock.acquire(['myKey], 1000); redisClient.set("myKey", "newValue") await lock.release(); } catch (e) { console.error(e); throw e; } }
> 
> But this way is wrong because we need to aquire a **resourceKey** like "myLokedResouce:myKey" and then make changes in our **key** (is tihis exemple "myKey") and after release the lock on "myLokedResouce:myKey". Now my code search by "resourceKey" to know if can makes changes in my "key" like:
> 
> const key = "project" const value = "CONFLICT" const resource = `locks:${key}` const lockTtl = 66000
> 
> async function lockAndSet(resource , lockTtl) { const lock = await redlock.acquire([resource], lockTtl)
> 
> try { await redisSet(key, value) console.log('Time finished, key unlocked!') await lock.release()
> 
> } catch (e) { console.log(e) } }
> 
> lockAndSet(resource, lockTtl)

This was also the solution for my case. The DOCS need updating, I've done so on this PR: https://github.com/mike-marcacci/node-redlock/pull/291

**Comment by MrFabio** [comment]
Solved it using a check for the lock expiration:
``` js
const now = new Date().getTime();
if (lock && lock.expiration > now) {
  await lock.release();
}
```
If the lock is expired (TTL), it is no longer in the cache, so don't release it.

**Comment by AJackTi** [comment]
> I have issue too! I have no idea. I read code and find `client.evalsha(args)` function throw error `Error: node_redis: The EVALSHA command contains a invalid argument type.`,then I have no idea

I encountered an error while debugging library code a few days ago. I tried my best to find solutions, but I couldn’t. Do you have a solution now?

**Comment by AJackTi** [comment]
> redlock

I used "ioredis" version "^4.2.0" and "redlock" version "^4.2.0". But it cannot lock the resource. I got the error message: `LockError {name: 'LockError', message: 'Exceeded 20 attempts to lock the resource`. Do you have solution for this issue?

**Comment by quallrum** [comment]
In case somebody made my mistake: i got the same error as OP (`ExecutionError: The operation was unable to achieve a quorum during its retry window.`) when `retryCount * retryDelay` is less then the lock duration:

```typescript
const redlock = new Redlock([redis], {
    retryCount: 15,
    retryDelay: 50,
});

const [result1, result2] = await Promise.all([
    redlock.using(['qwerty'], 3000, async () => {
        await sleep(1500);
        return 1;
    }),
    redlock.using(['qwerty'], 3000, async () => {
        await sleep(1500);
        return 2;
    }),
]);

console.log(result1, result2);
```

In the example above second lock will always fail since it cannot aquire lock, locked for 3000ms, within 15 * 50ms (750ms)

**Comment by Milan4e** [comment]
Was there a resolution for this ?

**Comment by ravi9989** [comment]
Make sure the code control still holds the redis lock before giving up the lock, the issue is losing the lock and then asking redlock to release the lock(which is already released automatically using timer).

**Comment by anteqkois** [comment]
Using above suggestion I have resolved this issue with these changes. The key is to overwrite `release` method and check if lock expired.

```ts
import Redlock from 'redlock'
import { redis } from '../storage/redis'

export const redlock = new Redlock([redis], {
  // The expected clock drift; for more details see:
  // http://redis.io/topics/distlock
  driftFactor: 0.01, // multiplied by lock ttl to determine drift time
  // The max number of times Redlock will attempt to lock a resource
  // before erroring.
  retryCount: 30,
  // the time in ms between attempts
  retryDelay: 2000, // time in ms
  // the max time in ms randomly added to retries
  // to improve performance under high contention
  // see https://www.awsarchitectureblog.com/2015/03/backoff.html
  retryJitter: 200, // time in ms
  // The minimum remaining time on a lock before an extension is automatically
  // attempted with the `using` API.
  automaticExtensionThreshold: 500, // time in ms
})

// Save the original acquire method
const originalAcquire = Redlock.prototype.acquire

// Override the release method for all lock instances
Redlock.prototype.acquire = async function (...args) {
  const duration = args[1] // this is a duration value

  // use the duration to create additional settings
  args[2] = {
    retryCount: Math.ceil((duration / 2_000) * 1.5),
    retryDelay: 2_000,
    ...args[2],
  }

  return originalAcquire.apply(this, args) // Call the original release method
}

// Save the original release method
const originalRelease = Redlock.prototype.release

// Override the release method for all lock instances
Redlock.prototype.release = async function (...args) {
  const now = new Date().getTime()

  if (args[0] && args[0].expiration > now) {
    // Check if the lock still exists
    return originalRelease.apply(this, args) // Call the original release method
  }

  return {
    attempts: [],
  }
}
```

**Comment by abdullah230695** [comment]
> Hi folks, I faced this problem, but was a mistake in my code.
> 
> I was trying to aquire and make a set in the same key, as:
> 
> const main = async () => { try { const lock = await redlock.acquire(['myKey], 1000); redisClient.set("myKey", "newValue") await lock.release(); } catch (e) { console.error(e); throw e; } }
> 
> But this way is wrong because we need to aquire a **resourceKey** like "myLokedResouce:myKey" and then make changes in our **key** (is tihis exemple "myKey") and after release the lock on "myLokedResouce:myKey". Now my code search by "resourceKey" to know if can makes changes in my "key" like:
> 
> const key = "project" const value = "CONFLICT" const resource = `locks:${key}` const lockTtl = 66000
> 
> async function lockAndSet(resource , lockTtl) { const lock = await redlock.acquire([resource], lockTtl)
> 
> try { await redisSet(key, value) console.log('Time finished, key unlocked!') await lock.release()
> 
> } catch (e) { console.log(e) } }
> 
> lockAndSet(resource, lockTtl)

You are right bro, thank u

**Comment by bspink** [comment]
It appears that this may have been addressed in the following PRs:
https://github.com/mike-marcacci/node-redlock/pull/274
PR: https://github.com/mike-marcacci/node-redlock/pull/276

These are linked to the issue https://github.com/mike-marcacci/node-redlock/issues/169 which seems to be the same issue seen here.

These PRs were merged to `main` in 2023, but the last NPM release for this package was in 2022.

Someone appears to have published a "temporary" package with that fix (and others) here https://www.npmjs.com/package/redlock-temp-fix

The company I'm working for is using this package and currently seeing this error quite a lot, so we're going to publish a private package based on `main` and test it out, but for others it might be worth trying out the above published package to see if things are fixed.

**Comment by sibelius** [comment]
what is the best way to debug this ?

**Comment by nghianvm** [comment]
I only use one redis instance. Why is this error reported? Does this really require a multi-redis setup, despite what the docs say?
