### ISSUE TITLE
await redlock.using will never resolve

### ISSUE THREAD

**Issue by SinanAkkoyun** [mike-marcacci/node-redlock#169]
Hi, I don't know what causes this behaviour, but no matter how I try to use your code, I am never getting it to work

```ts
redlock.using([`util:${this.settings.hostIP}`], minimalDelay+1, async signal => {
              const result = await stuff(ctx.params.cred) // takes approx 5s

              if (signal.aborted) {
                throw signal.error
              }
              return result
            })
```

I always error out:
```
ExecutionError: The operation was unable to achieve a quorum during its retry window.
 at Redlock._execute (/app/node_modules/redlock/dist/cjs/index.js:296:23)
 at async Redlock.acquire (/app/node_modules/redlock/dist/cjs/index.js:213:34)
attempts: [
 Promise { [Object] },
...,
Promise { [Object] }
 ]
```
And when I increase the tries before erroring out, it will just never resolve
What could I be doing wrong? Thanks

**Comment by SinanAkkoyun** [comment]
To further add to this, this happens from the beginning on, not even once does "stuff" run.

I am using one redis server, my app and the server in one docker-compose

**Comment by jakobo** [comment]
Just encountered this. We were able to work around this by using the `await lock.acquire()` api.

**Comment by arath17** [comment]
hello @mike-marcacci , this issue should be fixed with the [PR](https://github.com/mike-marcacci/node-redlock/pull/274) which got merged. We're waiting for you to release a new npm version for redlock with this fix ASAP as my team has a requirement for using auto extending locks.

**Comment by PomanoB** [comment]
Hello, @mike-marcacci , please, release new version with #274

**Comment by RGurevich** [comment]
Hi, @mike-marcacci , could you be so kind to release a new version with that fix, please?

**Comment by aduca98** [comment]
hey guys just wanted to chime in here, what is blocking this? I am also having issues with this same thing.

**Comment by temich** [comment]
https://github.com/mike-marcacci/node-redlock/pull/274#issuecomment-1610154289

**Comment by anteqkois** [comment]
@SinanAkkoyun @aduca98 
I have resolved this issue with these changes. The key is to overwrite `release` method and check if lock expired.

```ts
import Redlock from 'redlock'
import { redis } from '../storage/redis'

export const redlock = new Redlock([redis], {
  // The expected clock drift; for more details see:
  // http://redis.io/topics/distlock
  driftFactor: 0.01, // multiplied by lock ttl to determine drift time
  // The max number of times Redlock will attempt to lock a resource
  // before erroring.
  retryCount: 30,
  // the time in ms between attempts
  retryDelay: 2000, // time in ms
  // the max time in ms randomly added to retries
  // to improve performance under high contention
  // see https://www.awsarchitectureblog.com/2015/03/backoff.html
  retryJitter: 200, // time in ms
  // The minimum remaining time on a lock before an extension is automatically
  // attempted with the `using` API.
  automaticExtensionThreshold: 500, // time in ms
})

// Save the original acquire method
const originalAcquire = Redlock.prototype.acquire

// Override the release method for all lock instances
Redlock.prototype.acquire = async function (...args) {
  const duration = args[1] // this is a duration value

  // use the duration to create additional settings
  args[2] = {
    retryCount: Math.ceil((duration / 2_000) * 1.5),
    retryDelay: 2_000,
    ...args[2],
  }

  return originalAcquire.apply(this, args) // Call the original release method
}

// Save the original release method
const originalRelease = Redlock.prototype.release

// Override the release method for all lock instances
Redlock.prototype.release = async function (...args) {
  const now = new Date().getTime()

  if (args[0] && args[0].expiration > now) {
    // Check if the lock still exists
    return originalRelease.apply(this, args) // Call the original release method
  }

  return {
    attempts: [],
  }
}
```

**Comment by SinanAkkoyun** [comment]
You're a legend for sharing this despite of how old the issue is!
