### ISSUE TITLE
How to distinguish between initial quorom achievement and quorom renewal failures?

### ISSUE THREAD

**Issue by johnib** [mike-marcacci/node-redlock#185]
Hey,

Given the following code:

```javascript
    try {
      return await this.redLock.using(resources, lockRenewalTime, options, fn);
    } catch (err) {
        // err is always "ExecutionError: The operation was unable to achieve a quorum during its retry window" 
    }
```

Given the signal provided to `fn` is aborted, and then an exception is thrown from the `fn`, it is then caught in the above `catch` block.

In that `catch` block, I cannot determine whether it was the initial quorom achievement that failed, or quorom renewal that failed during the running period of `fn`.

The err would always be:

```log
error: ExecutionError: The operation was unable to achieve a quorum during its retry window.
    at Redlock._execute (/usr/src/app/node_modules/redlock/dist/cjs/index.js:296:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Redlock.using (/usr/src/app/node_modules/redlock/dist/cjs/index.js:474:13)
    at async LockManager.using (/usr/src/app/src/services/lock-manager.js:37:14)
```

I need that in order to decide on the subsequent behavior.
The initial quorom is a much softer error, while the latter one is something I have to handle differently.

Thanks for the help

**Comment by en-tcelvi** [comment]
This would also help me with some diagnostics :-)

**Comment by anteqkois** [comment]
@johnib 
I have resolved this issue with these changes. The key is to overwrite `release` method and check if lock expired.

```ts
import Redlock from 'redlock'
import { redis } from '../storage/redis'

export const redlock = new Redlock([redis], {
  // The expected clock drift; for more details see:
  // http://redis.io/topics/distlock
  driftFactor: 0.01, // multiplied by lock ttl to determine drift time
  // The max number of times Redlock will attempt to lock a resource
  // before erroring.
  retryCount: 30,
  // the time in ms between attempts
  retryDelay: 2000, // time in ms
  // the max time in ms randomly added to retries
  // to improve performance under high contention
  // see https://www.awsarchitectureblog.com/2015/03/backoff.html
  retryJitter: 200, // time in ms
  // The minimum remaining time on a lock before an extension is automatically
  // attempted with the `using` API.
  automaticExtensionThreshold: 500, // time in ms
})

// Save the original acquire method
const originalAcquire = Redlock.prototype.acquire

// Override the release method for all lock instances
Redlock.prototype.acquire = async function (...args) {
  const duration = args[1] // this is a duration value

  // use the duration to create additional settings
  args[2] = {
    retryCount: Math.ceil((duration / 2_000) * 1.5),
    retryDelay: 2_000,
    ...args[2],
  }

  return originalAcquire.apply(this, args) // Call the original release method
}

// Save the original release method
const originalRelease = Redlock.prototype.release

// Override the release method for all lock instances
Redlock.prototype.release = async function (...args) {
  const now = new Date().getTime()

  if (args[0] && args[0].expiration > now) {
    // Check if the lock still exists
    return originalRelease.apply(this, args) // Call the original release method
  }

  return {
    attempts: [],
  }
}
```
