### ISSUE TITLE
Not support redis 2.6.0 for set NX

### ISSUE THREAD

**Issue by wv1124** [mike-marcacci/node-redlock#50]
message:
   'ERR Error running script (call to f_862f31bf38e9b63ce28d6e9e5143551bb34ef981): Wrong number of args calling Redis command From Lua script ',
  command:
   { name: 'eval',
     args:
      [ 'return redis.call("set", KEYS[1], ARGV[1], "NX", "PX", ARGV[2])',
        '1',
        'shop_wv_test1',
        'f9a2445c012a1d2f2f38291a434c0731',
        '3000' ] } } undefined
2019-03-14 15:11:18,217 ERROR 1370 nodejs.LockError: Exceeded 10 attempts to lock the resource "shop_wv_test1".
    at /Users/wv/work/qianmi/api/shop/packages/shop-bff/node_modules/redlock/redlock.js:343:20
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Redlock._lock (/Users/wv/work/qianmi/api/shop/packages/shop-bff/node_modules/redlock/redlock.js:282:9)
    at Redlock.lock (/Users/wv/work/qianmi/api/shop/packages/shop-bff/node_modules/redlock/redlock.js:139:14)
    at Object.task (/Users/wv/work/qianmi/api/shop/packages/shop-bff/app/schedule/goods-name-index-all.ts:47:23)
name: "LockError"
message: "Exceeded 10 attempts to lock the resource \"shop_wv_test1\"."

**Comment by mike-marcacci** [comment]
Hi @wv1124, I think this is expected, as redis 2.6 [was superseded in 2013](http://download.redis.io/releases/). I'm going to close this issue, since I don't see a compelling reason to back-port it. That said, if you submitted a PR, I would certainly look at it.
